version: 2

linters:
  enable:
    - revive
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

run:
  timeout: 5m
  issues-exit-code: 1

linters-settings:
  revive:
    rules:
      - name: exported # Check for exported items without comments
        severity: warning
        arguments: []

exclude:
  - "generated"
  - "vendor"
