// Code generated by MockGen. DO NOT EDIT.
// Source: lookup/lookup.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTeamsLookup is a mock of TeamsLookup interface.
type MockTeamsLookup struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsLookupMockRecorder
}

// MockTeamsLookupMockRecorder is the mock recorder for MockTeamsLookup.
type MockTeamsLookupMockRecorder struct {
	mock *MockTeamsLookup
}

// NewMockTeamsLookup creates a new mock instance.
func NewMockTeamsLookup(ctrl *gomock.Controller) *MockTeamsLookup {
	mock := &MockTeamsLookup{ctrl: ctrl}
	mock.recorder = &MockTeamsLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsLookup) EXPECT() *MockTeamsLookupMockRecorder {
	return m.recorder
}

// ChannelNameFromID mocks base method.
func (m *MockTeamsLookup) ChannelNameFromID(teamID, channelID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChannelNameFromID", teamID, channelID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChannelNameFromID indicates an expected call of ChannelNameFromID.
func (mr *MockTeamsLookupMockRecorder) ChannelNameFromID(teamID, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChannelNameFromID", reflect.TypeOf((*MockTeamsLookup)(nil).ChannelNameFromID), teamID, channelID)
}

// TeamNameFromID mocks base method.
func (m *MockTeamsLookup) TeamNameFromID(teamID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeamNameFromID", teamID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TeamNameFromID indicates an expected call of TeamNameFromID.
func (mr *MockTeamsLookupMockRecorder) TeamNameFromID(teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeamNameFromID", reflect.TypeOf((*MockTeamsLookup)(nil).TeamNameFromID), teamID)
}
