// Code generated by MockGen. DO NOT EDIT.
// Source: messenger.go
//
// Generated by this command:
//
//	mockgen -source=messenger.go -destination=mocks/messenger.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	messenger "github.com/bautistv/posta-baut/pkg/messenger"
	gomock "go.uber.org/mock/gomock"
)

// MockMessenger is a mock of Messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
	isgomock struct{}
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// SendChannelMessage mocks base method.
func (m *MockMessenger) SendChannelMessage(ctx context.Context, teamID, channelID string, msg messenger.TeamsMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChannelMessage", ctx, teamID, channelID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendChannelMessage indicates an expected call of SendChannelMessage.
func (mr *MockMessengerMockRecorder) SendChannelMessage(ctx, teamID, channelID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChannelMessage", reflect.TypeOf((*MockMessenger)(nil).SendChannelMessage), ctx, teamID, channelID, msg)
}

// SendChatMessage mocks base method.
func (m *MockMessenger) SendChatMessage(ctx context.Context, chatID string, msg messenger.TeamsMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChatMessage", ctx, chatID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendChatMessage indicates an expected call of SendChatMessage.
func (mr *MockMessengerMockRecorder) SendChatMessage(ctx, chatID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChatMessage", reflect.TypeOf((*MockMessenger)(nil).SendChatMessage), ctx, chatID, msg)
}
