// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/posta_baut.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*SendMessageRequest_ChatMessage
	//	*SendMessageRequest_ChannelMessage
	MessageType   isSendMessageRequest_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_v1_posta_baut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetMessageType() isSendMessageRequest_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *SendMessageRequest) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.MessageType.(*SendMessageRequest_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *SendMessageRequest) GetChannelMessage() *ChannelMessage {
	if x != nil {
		if x, ok := x.MessageType.(*SendMessageRequest_ChannelMessage); ok {
			return x.ChannelMessage
		}
	}
	return nil
}

type isSendMessageRequest_MessageType interface {
	isSendMessageRequest_MessageType()
}

type SendMessageRequest_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type SendMessageRequest_ChannelMessage struct {
	ChannelMessage *ChannelMessage `protobuf:"bytes,2,opt,name=channel_message,json=channelMessage,proto3,oneof"`
}

func (*SendMessageRequest_ChatMessage) isSendMessageRequest_MessageType() {}

func (*SendMessageRequest_ChannelMessage) isSendMessageRequest_MessageType() {}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_v1_posta_baut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Represents a message to send in a chat (1:1 or group chat)
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_v1_posta_baut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Represents a message to send in a team channel
type ChannelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	mi := &file_v1_posta_baut_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelMessage) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ChannelMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_v1_posta_baut_proto protoreflect.FileDescriptor

const file_v1_posta_baut_proto_rawDesc = "" +
	"\n" +
	"\x13v1/posta_baut.proto\x12\n" +
	"posta_baut\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa9\x01\n" +
	"\x12SendMessageRequest\x12<\n" +
	"\fchat_message\x18\x01 \x01(\v2\x17.posta_baut.ChatMessageH\x00R\vchatMessage\x12E\n" +
	"\x0fchannel_message\x18\x02 \x01(\v2\x1a.posta_baut.ChannelMessageH\x00R\x0echannelMessageB\x0e\n" +
	"\fmessage_type\"T\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"J\n" +
	"\vChatMessage\x12\x1c\n" +
	"\achat_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06chatId\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tB\x03\xe0A\x02R\acontent\"q\n" +
	"\x0eChannelMessage\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12\"\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tchannelId\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tB\x03\xe0A\x02R\acontent2|\n" +
	"\fTeamsService\x12l\n" +
	"\vSendMessage\x12\x1e.posta_baut.SendMessageRequest\x1a\x1f.posta_baut.SendMessageResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/messages/sendB4Z2github.com/bautistv/posta-baut/internal/pb/v1;pbv1b\x06proto3"

var (
	file_v1_posta_baut_proto_rawDescOnce sync.Once
	file_v1_posta_baut_proto_rawDescData []byte
)

func file_v1_posta_baut_proto_rawDescGZIP() []byte {
	file_v1_posta_baut_proto_rawDescOnce.Do(func() {
		file_v1_posta_baut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_posta_baut_proto_rawDesc), len(file_v1_posta_baut_proto_rawDesc)))
	})
	return file_v1_posta_baut_proto_rawDescData
}

var file_v1_posta_baut_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_posta_baut_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: posta_baut.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: posta_baut.SendMessageResponse
	(*ChatMessage)(nil),         // 2: posta_baut.ChatMessage
	(*ChannelMessage)(nil),      // 3: posta_baut.ChannelMessage
}
var file_v1_posta_baut_proto_depIdxs = []int32{
	2, // 0: posta_baut.SendMessageRequest.chat_message:type_name -> posta_baut.ChatMessage
	3, // 1: posta_baut.SendMessageRequest.channel_message:type_name -> posta_baut.ChannelMessage
	0, // 2: posta_baut.TeamsService.SendMessage:input_type -> posta_baut.SendMessageRequest
	1, // 3: posta_baut.TeamsService.SendMessage:output_type -> posta_baut.SendMessageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_posta_baut_proto_init() }
func file_v1_posta_baut_proto_init() {
	if File_v1_posta_baut_proto != nil {
		return
	}
	file_v1_posta_baut_proto_msgTypes[0].OneofWrappers = []any{
		(*SendMessageRequest_ChatMessage)(nil),
		(*SendMessageRequest_ChannelMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_posta_baut_proto_rawDesc), len(file_v1_posta_baut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_posta_baut_proto_goTypes,
		DependencyIndexes: file_v1_posta_baut_proto_depIdxs,
		MessageInfos:      file_v1_posta_baut_proto_msgTypes,
	}.Build()
	File_v1_posta_baut_proto = out.File
	file_v1_posta_baut_proto_goTypes = nil
	file_v1_posta_baut_proto_depIdxs = nil
}
